version: '3.4'

services:
  bot:
    image: wpbotnet
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "19736:19736/tcp"
    restart: always
    volumes:
      - type: bind
        source: ./Data
        target: /data
        read_only: false
    stop_grace_period: 1m
